### PR TITLE
Add Homebrew formula

### PR DESCRIPTION
**Pull request by danielbayley**
Enable `brew install revolver`

### CODE REVIEW

**Comment by molovo** [comment]
Thanks very much for the PR, I've been meaning to sort this out for a while. I'm just putting together a deploy script to auto-update the formula when I push a new tag, and then I'll get this merged :)

**Comment by molovo** [comment]
@danielbayley I've merged this, but don't install just yet. I'm about to push the update script and may have to push tags a few times until it's working. I'll update this PR when I'm finished

**Comment by molovo** [comment]
Ha! I got the deploy script working, and then after the formula was updated with the new version, I realised that this won't work anyway because running `brew tap molovo/revolver` looks for a repo at `molovo/homebrew-revolver`. I'll create that repo and transfer the formula across.

Thanks again for the time you spent on this.

**Comment by danielbayley** [comment]
> I realised that this won't work anyway because running brew tap molovo/revolver looks for a repo at molovo/homebrew-revolver

@molovo Yeah for some reason [says so in the docs] to be able to just do `brew tap user/repo` that repo has to have the `homebrew-` prefix, otherwise the format has to be `brew tap user/repo url`  for it to work (which I put in the README)…

> molovo/homebrew-revolver. I'll create that repo and transfer the formula across.

Actually, considering this was done as a precursor to https://github.com/molovo/zunit/pull/71, it might be worth combining both formulas (formulae?) into a single `homebrew-molovo` repo or something like that and update the READMEs accordingly?

Then the install for both would just be the much more terse:

~~~ sh
brew tap molovo/whatever
brew install zunit # or just revolver
~~~
Then maybe you could even give the other dependency [`colors`] it's own formula… not sure if that'd be worthwhile though?

I'll probably end up using `zplug` in the end anyway! 😆

**Comment by molovo** [comment]
Ah yes, I ran `brew install molovo/revolver/revolver`, so I missed the URL you'd added in the README. The `molovo/homebrew-revolver` repo is now live, so you should be able to install this from `molovo/revolver/revolver`.

ZUnit will be a special case, as I'm about to go through the process of transferring it to [it's own organisation](https://github.com/zunit-zsh) so it'll have it's own tap there, with that and a few other things in it. I'll ping you when I've got that up and running.

**Comment by danielbayley** [comment]
Ok, cool.

**Pull request merged**
